package com.sampas.socbs.core.network.impl;
/**
 * An implementation of GraphGenerator used to generate a graph representing a
 * directed line network. Graphs are generated by supplying the generator with 
 * objects of type LineSegment via the add(Object) method. <BR>
 * <BR>
 * For each line segment added, an edge in the graph is created. The builder
 * records the end coordinates of each line added, and maintains a map of 
 * coordinates to nodes, creating nodes when neccessary.<BR>
 * <BR>
 * Edges created by the generator are of type BasicDirectedEdge and contain an 
 * object of type LineSegment.<BR>
 * Nodes created by the generator are of type BasicDirectedXYNode and contain 
 * an object of type Coordinate. 
 *
 * @see org.geotools.graph.structure.basic.SmpBasicDirectedXYNode
 * @see org.geotools.graph.structure.basic.BasicDirectedEdge
 * @see com.vividsolutions.jts.geom.LineSegment
 * @see com.vividsolutions.jts.geom.Coordinate
 * 
 * @author Justin Deoliveira, Refractions Research Inc, jdeolive@refractions.net
 *
 * @source $URL: http://svn.geotools.org/tags/2.4.4/modules/extension/graph/src/main/java/org/geotools/graph/build/line/BasicDirectedLineGraphGenerator.java $
 */
public class SmpBasicDirectedLineGraphGenerator extends SmpBasicLineGraphGenerator {
  
  /**
   * Constructs a new BasicDirectedLineGraphGenerator.
   */
  public SmpBasicDirectedLineGraphGenerator() {
    super();
    setGraphBuilder(new SmpBasicDirectedGraphBuilder());  
  } 
}
